JOKE_DEFAULT_URL = "http://www.jokeji.cn/jokehtml/bxnn/201403172304105.htm"
CARTOON_DEFAULT_URL = "http://www.xiaojiulou.com/sexi/3639.html"

#user input content type
CONSTANT_BASE = 1000
USER_CONTENT_TYPE_ERROR = -1
USER_CONTENT_TYPE_WHY = 0
USER_CONTENT_TYPE_CARTOON = 1
USER_CONTENT_TYPE_JOKE = 2
USER_CONTENT_TYPE_JZW = 3
USER_CONTENT_TYPE_MUSIC = 4
USER_CONTENT_TYPE_JZW_ANSWER = CONSTANT_BASE+USER_CONTENT_TYPE_JZW
USER_CONTENT_TYPE_MUSIC_SEARCH = CONSTANT_BASE+USER_CONTENT_TYPE_MUSIC
USER_CONTENT_TYPE_CX = "CX"

